config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#about'

  get 'notes', to: 'notes#index'
  post 'notes', to: 'notes#create'
  get 'notes/new', to: 'notes#new', as: :new_note
  get 'notes/:id', to: 'notes#show', as: :note
  patch 'notes/:id', to: 'notes#update'
  delete 'notes/:id', to: 'notes#destroy'
  get 'notes/:id/edit', to: 'notes#edit', as: :edit_note

  get 'items', to: 'items#index'
  post 'items', to: 'items#create'
  get 'items/new', to: 'items#new', as: :new_item
  get 'items/:id', to: 'items#show', as: :item
  patch 'items/:id', to: 'items#update'
  delete 'items/:id', to: 'items#destroy'
  get 'items/:id/edit', to: 'items#edit', as: :edit_item

  root 'pages#home'
  
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :expected_cost, comparison: { less_than: 50 }
end

app/models/note.rb
class Note < ApplicationRecord 
    validates :name, length: { in: 3..7 }
    validates :body, presence: true
end

app/models/user.rb
class User 
    attr_reader :name, :hobbies, :show_hidden_info

    def initialize(name:, hobbies: [], show_hidden_info: false)
        @name = name
        @hobbies = hobbies
        @show_hidden_info = show_hidden_info
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :destroy]

    def index
        @items = Item.all
    end

    def show
    end

    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(item_params)

        if @item.save
            redirect_to items_url
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end
    
    def update
        if @item.update(item_params)
            redirect_to items_url
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @item.delete

        redirect_to items_url
    end

    private
    
    def item_params
        params.require(:item).permit(:title, :expected_cost, :is_done)
    end

    def set_item
        @item = Item.find(params[:id])
    end
    
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :set_note, only: [:show, :edit, :update, :destroy]

    def index
        @notes = Note.all
    end

    def show
    end

    def new
        @note = Note.new
    end
    
    def create
        # valid - new action - new view - (submit form) - create action - show action - show view 
        # invalid - new action - new view - (submit form) - create action - new view 
        @note = Note.new(note_params)

        if @note.save
            redirect_to @note
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def edit
    end
    
    def update
        if @note.update(note_params)
            redirect_to @note
        else
            render 'edit', status: :unprocessable_entity
        end

    end

    def destroy
        @note.delete

        redirect_to notes_url

    end

    private

    def note_params
        params.require(:note).permit(:name, :body)
    end
    
    def set_note
        @note = Note.find(params[:id])
    end

 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @user = User.new(
            name: 'Jana Vorekova',
            hobbies: ['snowboard', 'programming', 'swimming '],
            show_hidden_info: true
            )
        # nemusím písať 'pagess/about, lebo sa to nachádza v PAGEScontroller - nájde vo views PAGES'
        # nemusím písať ani render 'about', lebo Rails vie, že keď zavolám def about end, tak to vygeneruje about.html samo. 
    end

    def home
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, class: 'grid grid-cols-1 gap-y-6' do |f| %>
    <% if @item.errors.any? %>
        <ul>
            <% @item.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>    
    <% end %>
    <div>
        <%= f.label :title, class: 'text-gray-600 text-sm font-medium' %>
        <%= f.text_field :title, class: 'w-full border-0 ring-1 px-3 py-1.5 ring-gray-300 rounded-md' %>
    </div>
    <div>
        <%= f.label :expected_cost, class: 'text-gray-600 text-sm font-medium' %>
        <%= f.number_field :expected_cost, step: 0.01, class: 'w-full border-0 ring-1 px-3 py-1.5 ring-gray-300 rounded-md' %>
    </div>
    <div>
        <%= f.label :is_done, class: 'text-gray-600 text-sm font-medium' %>
        <%= f.check_box :is_done, class: 'ml-2 border-0 ring-1 ring-gray-300 rounded-md' %>
    </div>
    <div>
        <%= f.submit submit_text, class: 'px-4 py-2 bg-indigo-600 text-white rounded-md' %>
    </div>
<% end %>

app/views/items/create.html.erb
create 

app/views/items/edit.html.erb
<h1 class='text-2xl font-semibold'>Editing item</h1>

<div class='mt-6'>
    <%= render 'form', submit_text: 'Woohoo, update!' %>
</div>
<%= link_to 'Cancel', @item, class: 'inline-block mt-2' %> 

app/views/items/index.html.erb
<%= link_to '<- Home', root_path, class: 'text-sm text-gray-400' %> 

<div class='flex justify-between items-center'>
    <h1 class='text-3xl font-semibold'>Items</h1>
    <%= link_to 'New Item', new_item_path, class: 'px-4 py-2 bg-indigo-600 text-white rounded-md' %> 
</div>

<section class='mt-6 grid grid-cols-1 sm:grid-cols-3 xl:grid-cols-6 gap-x-8 gap-y-6'>
    <% @items.each do |item| %>
        <% if item.is_done? %> 
            <div class='flex justify-between items-center bg-gray-50 shadow-md p-4 border-t-4 border-indigo-200 rounded-lg transition duration-300 hover:shadow-lg'>
                <div>
                    <h2 class='text-lg font-medium'><%= item.title %></h2>
                    <p><%=item.expected_cost %></p>
                </div>
                <div>
                    <%= button_to 'Delete', item, method: :delete, class: 'px-4 py-2 text-gray-600 bg-rose-100 text-rose-500 rounded-md' %>
                </div>
            </div>
        <% else %>
            <div class='flex justify-between items-center shadow-md p-4 bg-gray-50 rounded-lg transition duration-300 hover:shadow-lg'>
                <div>
                    <h2 class='text-lg font-medium'><%= item.title %></h2>
                    <p><%=item.expected_cost %></p>
                </div>
                <div>
                    <%= button_to 'Done!', item, method: :patch, params: {item: {is_done: true} }, class: 'px-4 py-2 text-gray-600 border border-gray-300 rounded-md' %> 
                </div>
            </div>
        <% end %>
    <% end %>
</section>

app/views/items/new.html.erb
<h1 class='text-2xl font-semibold'>New item</h1>

<div class='mt-6'>
    <%= render 'form', submit_text: 'Create item' %>
</div>
<%= link_to 'Back to items', items_path, class: 'inline-block mt-2' %> 

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
<strong>Expected cost:</strong> <%= @item.expected_cost %><br />
<strong>Is done:</strong> <%= @item.is_done %>
<br>
<%= link_to 'Back to items', items_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-12 p-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: @note, class: 'grid grid-cols-1 gap-y-6' do |f| %>
    <% if @note.errors.any? %>
        <ul>
            <% @note.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>    
    <% end %>
    <div>
        <%= f.label :name, class: 'text-gray-600 text-sm font-medium' %>
        <%= f.text_field :name, class: 'w-full border-0 ring-1 px-3 py-1.5 ring-gray-300 rounded-md' %>
    </div>
    <div>
        <%= f.label :body , class: 'text-gray-600 text-sm font-medium'%>
        <%= f.text_area :body, class: 'mt-1 w-full border-0 ring-1 px-3 py-1.5 ring-gray-300 rounded-md' %>
    </div>
    <div>
        <%= f.submit submit_text, class: 'px-4 py-2 bg-indigo-600 text-white rounded-md' %>
    </div>
<% end %>

app/views/notes/create.html.erb
create  

app/views/notes/edit.html.erb
<h1 class= 'text-2xl font-semibold'>Editing note</h1>

<div class='mt-6'>
    <%= render 'form', submit_text: 'Woohoo update!' %>
</div> 

<%= link_to 'Cancel', @note, class: 'inline-block mt-2' %> 

app/views/notes/index.html.erb
<%= link_to '<- Home', root_path, class: 'text-sm text-gray-400' %> 

<div class='flex justify-between items-center'>
    <h1 class='text-3xl font-semibold'>Notes</h1>
    <%= link_to 'New Note', new_note_path, class: 'px-4 py-2 bg-indigo-600 text-white rounded-md' %> 
</div>


<table class='mt-6 w-full'>
    <thead>
        <tr class='bg-gray-100 text-left'>
            <th class='py-3 px-3'>ID</th>
            <th>Name</th>
            <th>Body</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @notes.each do |note| %>
            <tr class='border-t border-gray-100'>
                <td class='py-2 px-3'><%= note.id %></td>
                <td><%= link_to note.name, note_path(id: note.id) %></td>
                <td><%= note.body %></td> 
                <td>
                    <div class='flex'>
                        <%= link_to 'Edit', edit_note_path(id: note.id), class: 'px-3 py-1.5 text-gray-500 border border-gray-300 rounded-md' %>
                        <%= button_to 'Delete', note, method: :delete, class: 'ml-2 px-3 py-1.5 bg-rose-100 text-rose-400 rounded-md' %> 
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/notes/new.html.erb
<h1 class='text-2xl font-semibold'>New note</h1>

<div class='mt-6'>
<%= render 'form', submit_text: 'Let me note this!' %>
</div>

<%= link_to 'Cancel', notes_path, class: 'inline-block mt-2' %> 

app/views/notes/show.html.erb
<%= link_to '<- Back to notes', notes_path, class: 'text-sm text-gray-400' %> 
<h1 class=' mt-1 text-2xl font-semibold'><%= @note.name %></h1>
<p class='mt-6'><%= @note.body %></p>

app/views/pages/about.html.erb
<h1> <%= @user.name %> </h1>
<p>This is my profile...</p>
<h2>My hobbies:</h2>

<ul>
    <% @user.hobbies.each do |hobby| %>
        <li> <%= hobby %> </li>
    <% end %>
</ul>

<% if @user.show_hidden_info %>
        'I am 31 years old.'
<% end %>

app/views/pages/home.html.erb
<h1 class="text-3xl font-semibold">Welcome to my homepage!</h1>

<div class="mt-4 flex flex-col">
    <%= link_to '-> Notes', notes_path %>
    <%= link_to '-> Items', items_path %>
</div>